// Cross-surface conformance (§Testing): the wasm engine must compute
// byte-identical results to native against shared vectors generated by the
// native build (`cargo run -p asp-core --example gen_vectors`). If the wasm
// fold/merge/identity ever skews from native, these fail.

import { expect, test } from 'bun:test';
import { contentHash, foldFiles, merge3Bytes, nodeIdHex, sshPubkey } from '../src/index.ts';
import vectors from '../test-vectors.json';

function hexToBytes(h: string): Uint8Array {
  const out = new Uint8Array(h.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = Number.parseInt(h.slice(i * 2, i * 2 + 2), 16);
  return out;
}
const b = (s: string) => new TextEncoder().encode(s);

test('identity (node id + ssh pubkey) matches native', () => {
  const seed = hexToBytes(vectors.seed_hex);
  expect(nodeIdHex(seed)).toBe(vectors.node_id);
  expect(sshPubkey(seed, 'asp')).toBe(vectors.ssh_pubkey);
});

test('content hash matches native', () => {
  expect(contentHash(b('hello\n'))).toBe(vectors.content_hash_hello);
});

test('deterministic fold matches native byte-for-byte', () => {
  const out = JSON.parse(foldFiles(JSON.stringify(vectors.fold.rows), JSON.stringify(vectors.fold.blobs)));
  expect(out).toEqual(vectors.fold.expected_files);
});

test('3-way merge matches native (text clean-resolve, code conflict-surface)', () => {
  expect(Array.from(merge3Bytes('text', b('x\n'), b('ours\n'), b('theirs\n')))).toEqual(
    vectors.merge.text_same_region,
  );
  expect(Array.from(merge3Bytes('code', b('x\n'), b('ours\n'), b('theirs\n')))).toEqual(
    vectors.merge.code_same_region,
  );
});
